### ISSUE TITLE
브랜치 새로 따기

### ISSUE THREAD

**Issue by hxunz** [maengoose/routinary#5]
브랜치 새로 생성하게되면
지금 features/get-awards에서 작성한 코드도 
새로 생성한 브랜치에 적용되어있나요?
@Kihyun92

**Comment by Kihyun92** [comment]
브랜치를 어디서 생성하냐에 따라 달라져요.
features/get-awards가 main 브랜치로 머지되지 않은 상태에서 main브랜치에서 피쳐를 따면 당연히 코드가 없을거구요.
필요하다면 main이 아닌 features/get-awards에서 자식 브랜치를 따면 됩니다. 이때 새 브랜치의 PR을 생성할땐 main이 아닌 features/get-awards가 부모이니까 거기를 베이스 브랜치로해서 머지되도록 해주면 됩니다.
<img width="952" alt="image" src="https://user-images.githubusercontent.com/35797540/175972851-b277099b-5eff-4663-b3d2-87d2ecc2822a.png">
(만약 새로딴 브랜치보다 features/get-awards가 먼저 머지됐다면 리베이스를 하거나 새로 만든 브랜치 PR의 베이스를 main으로 바꾸면됨)

추가로 cherry pick 등 다양한 방법이 git에는 존재해요. 같이 공부 고고합시다
